version: '3.5'

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        image: mariadb:inception
        env_file:
            - .env
        restart: always
        volumes:
            - data_db:/var/lib/mysql/
        ports:
            - 3306:3306
        networks:
            - nat
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        image: nginx:inception
        env_file:
            - .env
        ports:
            - 443:443
        restart: on-failure
        depends_on:
            - wordpress
        volumes:
            - data:/var/www/html/
        networks:
            - nat
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        image: wordpress:inception
        env_file:
            - .env
        restart: always
        depends_on:
            - mariadb
        ports:
            - 9000:9000
        volumes:
            - data:/var/www/html/
        networks:
            - nat
    adminer:
        build: ./requirements/bonus/adminer
        container_name: adminer
        image: adminer:inception
        restart: always
        ports:
            - 8080:8080
        networks:
            - nat
    redis:
        build: ./requirements/bonus/Redis
        container_name: redis
        image: redis:inception
        restart: on-failure
        ports:
            - '6379:6379'
        networks:
            - nat
volumes:
    data:
        driver: local
        driver_opts:
            device : /Users/mmoumni/Desktop/INCEPTION/srcs/data
            type : none
            o: bind
    data_db:
        driver: local
        driver_opts:
            device: /Users/mmoumni/Desktop/INCEPTION/srcs/data_db
            type: none
            o: bind
networks:
    nat:
        driver: bridge
    