version: '3.7'

services:
    mariadb:
        build: ./requirements/mariadb/
        image: mariadb
        container_name: mariadb
        env_file:
            - .env
        restart: always
    wordpress:
        build: ./requirements/wordpress/
        image: wordpress
        container_name: wordpress
        env_file:
            - .env