version: '3.5'

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        image: mariadb:inception
        env_file:
            - .env
        restart: always
        volumes:
            - data_db:/var/lib/mysql/
        ports:
            - '3306:3306'
        networks:
            - nat
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        image: nginx:inception
        env_file:
            - .env
        ports:
            - '443:443'
        restart: on-failure
        depends_on:
            - wordpress
        volumes:
            - data_wp:/var/www/html/
        networks:
            - nat
    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        image: wordpress:inception
        env_file:
            - .env
        restart: always
        depends_on:
            - mariadb
        ports:
            - '9000:9000'
        volumes:
            - data_wp:/var/www/html/
        networks:
            - nat
    adminer:
        build: ./requirements/bonus/adminer
        container_name: adminer
        image: adminer:inception
        restart: always
        ports:
            - '8081:8081'
        networks:
            - nat
    redis:
        build: ./requirements/bonus/Redis
        container_name: redis
        image: redis:inception
        restart: on-failure
        ports:
            - '6379:6379'
        networks:
            - nat
    cadvisor:
        build: ./requirements/bonus/cadvisor
        container_name: cadvisor
        image: cadvisor:inception
        restart: on-failure
        ports:
            - '8080:8080'
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"
        networks:
            - nat
    static_stite:
        build: ./requirements/bonus/static_site
        container_name: static_site
        image: static_site:inception
        restart: on-failure
        ports:
            - '80:80'
        networks:
            - nat
    ftp:
        build: ./requirements/bonus/FTP
        container_name: ftp
        image: ftp:inception
        restart: on-failure
        ports:
            - '21:21'
            - '30000-30009:30000-30009'
            - '20:20'
        env_file:
            - .env
        volumes:
            - data_wp:/home/moumniVolum/ftp
        depends_on:
            - wordpress
        networks:
            - nat
volumes:
    data_wp:
        driver: local
        driver_opts:
            device : /home/login/data/data_wp
            type : none
            o: bind
    data_db:
        driver: local
        driver_opts:
            device: /home/login/data/data_db
            type: none
            o: bind
networks:
    nat:
        driver: bridge
    